"""Triggers inverted-index strategy.

For every `*.md` under `target_dir`, read the `triggers:` frontmatter list and
emit a YAML map of `trigger -> [relative paths]`. Optionally validates triggers
against a canonical set.

Config shape (see references-src/index-configs/triggers.yaml):

    strategy: triggers
    target_dir: guidelines
    output: index/triggers.yaml
    canonical_triggers:
      - writing-tests
      - ...
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date, datetime, timezone
from pathlib import Path

from ..core.deps import require
from ..core.frontmatter import parse
from ._shared import SKIP_FILENAMES

yaml = require("yaml")


def generate(config: dict, root: Path, today: date) -> tuple[str, dict]:
    target = root / config["target_dir"]
    canonical: set = set(config.get("canonical_triggers", []) or [])

    trigger_map: dict[str, list[str]] = defaultdict(list)
    files_total = 0
    files_with_triggers = 0
    warnings: list[str] = []

    for md in sorted(target.rglob("*.md")):
        if md.name in SKIP_FILENAMES:
            continue
        files_total += 1
        fm = parse(md.read_text(encoding="utf-8"))
        if not fm.had_frontmatter:
            continue
        triggers = fm.data.get("triggers") or []
        if not isinstance(triggers, list) or not triggers:
            continue
        files_with_triggers += 1
        rel_path = str(md.relative_to(root))
        for t in triggers:
            if canonical and t not in canonical:
                warnings.append(f"non-canonical trigger '{t}' in {rel_path}")
            trigger_map[t].append(rel_path)

    sorted_map = {k: sorted(v) for k, v in sorted(trigger_map.items())}
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    header_lines = [
        "# Auto-generated by `cookbook update` (strategy: triggers)",
        "# Do not edit manually — re-run `cookbook update` to regenerate.",
        f"# Generated: {now}",
        "",
    ]
    body = yaml.safe_dump(sorted_map, default_flow_style=False, sort_keys=False)
    text = "\n".join(header_lines) + body

    counts = {
        "files_total": files_total,
        "files_with_triggers": files_with_triggers,
        "unique_triggers": len(sorted_map),
        "warnings": warnings,
    }
    return text, counts
