#!/usr/bin/env npx tsx
/**
 * seed-d1.ts
 *
 * Reads scripts/tools.json, generates SQL INSERT statements, and executes
 * them against D1 (local or remote).
 *
 * Usage:
 *   npx tsx scripts/seed-d1.ts          # remote D1
 *   npx tsx scripts/seed-d1.ts --local  # local D1
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { execFileSync } from "node:child_process";

// ---------------------------------------------------------------------------
// Types (matching parse-research.ts output)
// ---------------------------------------------------------------------------

interface ToolEntry {
  id: string;
  name: string;
  url: string | null;
  github_url: string | null;
  description: string;
  install_command: string | null;
  category: string;
  subcategory: string | null;
  loop_phases: string;
  integration_method: string | null;
  platforms: string | null;
  languages: string | null;
  source_file: string;
}

// ---------------------------------------------------------------------------
// SQL escaping
// ---------------------------------------------------------------------------

function sqlEscape(value: string | null): string {
  if (value === null || value === undefined) return "NULL";
  // Replace single quotes with two single quotes
  const escaped = value.replace(/'/g, "''");
  return `'${escaped}'`;
}

// ---------------------------------------------------------------------------
// Generate SQL
// ---------------------------------------------------------------------------

function generateSQL(tools: ToolEntry[]): string {
  const lines: string[] = [];

  lines.push("-- Auto-generated by seed-d1.ts");
  lines.push(`-- ${tools.length} tools from scripts/tools.json`);
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push("");

  // Clean slate: delete tools (FTS triggers handle sync automatically)
  lines.push("-- Clear existing data");
  lines.push("DELETE FROM tools;");
  lines.push("");

  // Insert tools
  lines.push("-- Insert tools");
  for (const tool of tools) {
    const cols = [
      "id",
      "name",
      "url",
      "github_url",
      "description",
      "install_command",
      "category",
      "subcategory",
      "loop_phases",
      "integration_method",
      "platforms",
      "languages",
      "source_file",
    ];
    const vals = [
      sqlEscape(tool.id),
      sqlEscape(tool.name),
      sqlEscape(tool.url),
      sqlEscape(tool.github_url),
      sqlEscape(tool.description),
      sqlEscape(tool.install_command),
      sqlEscape(tool.category),
      sqlEscape(tool.subcategory),
      sqlEscape(tool.loop_phases),
      sqlEscape(tool.integration_method),
      sqlEscape(tool.platforms),
      sqlEscape(tool.languages),
      sqlEscape(tool.source_file),
    ];
    lines.push(`INSERT INTO tools (${cols.join(", ")}) VALUES (${vals.join(", ")});`);
  }
  lines.push("");

  // Update category counts
  lines.push("-- Update category tool counts");
  lines.push(
    "UPDATE categories SET tool_count = (SELECT COUNT(*) FROM tools WHERE tools.category = categories.slug);"
  );
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const scriptDir = dirname(import.meta.url.replace("file://", ""));
  const toolsPath = join(scriptDir, "tools.json");
  const sqlPath = join(scriptDir, "seed.sql");
  const isLocal = process.argv.includes("--local");

  // Read tools.json
  console.log(`\nReading ${toolsPath}...`);
  let tools: ToolEntry[];
  try {
    tools = JSON.parse(readFileSync(toolsPath, "utf-8"));
  } catch {
    console.error(
      `Error: Could not read tools.json. Run "npx tsx scripts/parse-research.ts" first.`
    );
    process.exit(1);
  }
  console.log(`  ${tools.length} tools loaded`);

  // Generate SQL
  console.log(`\nGenerating SQL...`);
  const sql = generateSQL(tools);
  writeFileSync(sqlPath, sql);
  console.log(`  Written to ${sqlPath} (${sql.length} bytes)`);

  // Execute against D1 using execFileSync (no shell injection risk)
  const mode = isLocal ? "local" : "remote";
  const args = ["wrangler", "d1", "execute", "tools-db"];
  if (isLocal) args.push("--local");
  args.push(`--file=${sqlPath}`);

  console.log(`\nExecuting against D1 (${mode})...`);
  console.log(`  $ npx ${args.join(" ")}\n`);

  try {
    execFileSync("npx", args, {
      cwd: join(scriptDir, ".."),
      stdio: "inherit",
      timeout: 120_000,
    });
  } catch {
    console.error(`\nD1 execution failed. The SQL file is still at ${sqlPath}`);
    console.error(`You can run it manually: npx ${args.join(" ")}`);
    process.exit(1);
  }

  console.log(`\nDone. ${tools.length} tools seeded to D1 (${mode}).`);
}

main();
