#!/usr/bin/env python3
"""Generate index/triggers.yaml from guideline frontmatter triggers fields."""

import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import yaml


CANONICAL_TRIGGERS = {
    "writing-tests", "error-handling", "new-module", "api-integration",
    "ai-api-integration", "data-modeling", "database-operations",
    "ui-implementation", "authentication", "input-handling", "networking",
    "concurrency", "logging", "security-review", "performance-optimization",
    "accessibility", "internationalization", "feature-flags",
    "platform-integration", "code-review", "pre-commit", "pre-pr",
    "dependency-management", "configuration", "offline-support",
    "skill-authoring", "recipe-authoring", "schema-design",
}


def parse_frontmatter(path: Path) -> dict:
    """Extract YAML frontmatter from a markdown file."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.index("---", 3)
    return yaml.safe_load(text[3:end]) or {}


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    guidelines_dir = repo_root / "guidelines"
    output_path = repo_root / "index" / "triggers.yaml"

    skip_names = {"INDEX.md", "index.md", "references.md"}
    trigger_map: dict[str, list[str]] = defaultdict(list)
    total = 0
    with_triggers = 0
    warnings = []

    for md_file in sorted(guidelines_dir.rglob("*.md")):
        if md_file.name in skip_names:
            continue
        total += 1
        fm = parse_frontmatter(md_file)
        triggers = fm.get("triggers", [])
        if not triggers:
            continue
        with_triggers += 1
        rel_path = str(md_file.relative_to(repo_root))
        for trigger in triggers:
            if trigger not in CANONICAL_TRIGGERS:
                warnings.append(f"  WARNING: non-canonical trigger '{trigger}' in {rel_path}")
            trigger_map[trigger].append(rel_path)

    # Sort triggers and their guideline lists
    sorted_map = {k: sorted(v) for k, v in sorted(trigger_map.items())}

    output_path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    header = (
        f"# Auto-generated by scripts/generate-trigger-index.py\n"
        f"# Do not edit manually — regenerate with: python3 scripts/generate-trigger-index.py\n"
        f"# Generated: {now}\n\n"
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(sorted_map, f, default_flow_style=False, sort_keys=False)

    unique_triggers = len(sorted_map)
    print(f"Processed {total} guidelines")
    print(f"  With triggers: {with_triggers}")
    print(f"  Unique triggers: {unique_triggers}")
    print(f"  Output: {output_path}")
    for w in warnings:
        print(w)


if __name__ == "__main__":
    main()
